### ISSUE TITLE
Is the paper available？

### ISSUE THREAD

**Issue by 869277160** [CZ-TAO12/MIM#1]
Hi there, I see you published a wonderful work on IDP. I'd like to know where I can see the full text of this paper:" Enhancing Information Diffusion Prediction with Cross-Cascade Hypergraph and Past-Future Knowledge Distillation"?

**Comment by CZ-TAO12** [comment]
Hi, thank you for your attention. This paper is currently undergoing the review process for a journal, and as a result, I am unable to provide you with the full text at this time. If you have any questions or would like to discuss topics related to IDP, feel free to contact me via email, QQ, or WeChat. This is my e-mail：zhangtao.cheng@outlook.com.

**Comment by 869277160** [comment]
Deeply thanks for your reply, I will check the code first. I have not seen works on improving Transformers in IDP for a long time.
